name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java 11 build, test, deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Start MongoDB for integration test
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
          
      - name: Build, test and package project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR info
        run: mvn -B verify 
      
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/p4_backend:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/p4_backend:latest
        
      - name: Trigger Jenkins Job
        uses: sbitio/trigger-jenkins-job@master
        with:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JENKINS_HOST: ${{ secrets.JENKINS_HOST }}
          JENKINS_JOB: ${{ secrets.JENKINS_JOB }}        
 
